# Generated by Django 3.2.9 on 2021-11-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=8)),
                ('nombre', models.TextField()),
                ('fechaNacimiento', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('localidad', models.TextField()),
                ('sexo', models.CharField(max_length=1)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCamas', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('tipo', models.TextField()),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=8)),
                ('nombre', models.TextField()),
                ('telefono', models.TextField()),
                ('direccion', models.TextField()),
                ('localidad', models.TextField()),
                ('sueldo', models.IntegerField()),
                ('observacion', models.TextField()),
            ],
        ),
    ]
