# Generated by Django 3.2.9 on 2021-11-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='direccion',
            field=models.TextField(null=True),
        ),
    ]
