# Generated by Django 3.2.9 on 2021-11-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendedor_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
    ]
